# Generated by Django 5.1.2 on 2024-12-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishTexts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TurkishTexts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadedEnglishTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadedTurkishTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.IntegerField()),
            ],
        ),
    ]
